FROM ubuntu:xenial

RUN apt update && apt upgrade -y
RUN apt install --assume-yes \
    zip \
    build-essential \
    git-core \
    subversion \
    cmake \
    automake \
    libtool \
    clang \
    libxrandr-dev \
    libxi-dev \
    libglm-dev \
    libgsl0-dev \
    libatlas3-base \
    libzmq3-dev \
    libsnappy-dev \
    libgphoto2-dev \
    libglfw3-dev \
    libxinerama-dev \
    libxcursor-dev \
    python3-dev \
    libavformat-dev \
    libavcodec-dev \
    libavutil-dev \
    libswscale-dev \
    portaudio19-dev \
    libopencv-dev
